### ISSUE TITLE
waterfall() function gives error

### ISSUE THREAD

**Issue by kb472** [griffithlab/GenVisR#325] opened 2018-03-15 18:03 UTC
Hello,
I have a data frame that I'm trying to use for plotting using the custom option. My data frame looks like this:
```{r}
> head(shortT001)
  sample  gene     variant_class
1   T001 SCYL3            Silent
2   T001 SCYL3            Silent
3   T001   FGR Missense_Mutation
4   T001   CFH Missense_Mutation
5   T001   CFH Missense_Mutation
6   T001   CFH Missense_Mutation

unique(shortT001$variant_class)
 [1] "Silent"            "Missense_Mutation" "Intron"           
 [4] "3'UTR"             "5'UTR"             "Frame_Shift_Ins"  
 [7] "Frame_Shift_Del"   "Splice_Site"       "Nonsense_Mutation"
[10] "RNA"               "Nonstop_Mutation"  NA                 
[13] "In_Frame_Del"      "In_Frame_Ins"      "3'Flank"          
[16] "IGR"               "5'Flank"        

most_deleterious1 <- c("Nonsense_Mutation", "Frame_Shift_Ins", "Frame_Shift_Del", "Translation_Start_Site", 
                      "Splice_Site", "Nonstop_Mutation",
                      "In_Frame_Ins",
                      "In_Frame_Del", 
                      "Missense_Mutation",
                      "5'Flank",
                      "3'Flank",
                      "5'UTR", "3'UTR", "RNA", "Intron", "IGR", "Silent","Targeted_Region")
#another way to set list of delerious mutations
most_deleterious2 <- as.character(unique(shortT001$variant_class))

waterfall(shortT001, fileType = "Custom", variant_class_order = most_deleterious1, mainXlabel = TRUE, rmvSilent = T)
Checking if input is properly formatted...
Detected "Custom" file_type flag, looking for correct column names...
Calculating frequency of mutations...
Removing silent mutations...
setting mutation hierarchy...
Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels, : factor level [2] is duplicated

waterfall(shortT001, fileType = "Custom", variant_class_order = most_deleterious2, mainXlabel = TRUE, rmvSilent = T)
Checking if input is properly formatted...
Detected "Custom" file_type flag, looking for correct column names...
Calculating frequency of mutations...
Removing silent mutations...
setting mutation hierarchy...
Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels, : factor level [2] is duplicated
```
Quesitons
1) I'm not sure why its giving me an error . Could you please help figure this out ?
2) For every combination of gene and sampleid, can the data frame only one entry for "variant_Class", or can there be multiple entries ?

Thanks, K

**Comment by zlskidmore** [comment] 2018-03-15 18:25
Can you send me the output of `sessionInfo()` also can you run the following example code and let me know if that works:

```R
library(GenVisR)
tmp <- brcaMAF

tmp <- tmp[,c("Hugo_Symbol", "Variant_Classification", "Tumor_Sample_Barcode")]
colnames(tmp) <- c("gene", "variant_class", "sample")

waterfall(tmp, fileType="Custom", variant_class_order=as.character(unique(tmp$variant_class)), mainXlabel=TRUE,rmvSilent=T)
```

**Comment by zlskidmore** [comment] 2018-03-15 18:27
to answer your second question for every combination of sample/gene there can be only one "variant_class" the parameter `variant_class_order` is what determines what "variant_class" in such cases

**Comment by kb472** [comment] 2018-03-15 18:35
Thanks for your quick message.
```{r}
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] GenVisR_1.8.0        data.table_1.10.4-3  maftools_1.4.25     
[4] Biobase_2.38.0       BiocGenerics_0.24.0  BiocInstaller_1.28.0

loaded via a namespace (and not attached):
 [1] bitops_1.0-6               matrixStats_0.53.1         bit64_0.9-7               
 [4] doParallel_1.0.11          RColorBrewer_1.1-2         progress_1.1.2            
 [7] httr_1.3.1                 GenomeInfoDb_1.14.0        tools_3.4.3               
[10] R6_2.2.2                   DBI_0.8                    lazyeval_0.2.1            
[13] colorspace_1.3-2           GetoptLong_0.1.6           gridExtra_2.3             
[16] prettyunits_1.0.2          RMySQL_0.10.14             bit_1.1-12                
[19] compiler_3.4.3             DelayedArray_0.4.1         pkgmaker_0.22             
[22] labeling_0.3               rtracklayer_1.38.3         slam_0.1-42               
[25] scales_0.5.0               NMF_0.21.0                 stringr_1.3.0             
[28] digest_0.6.15              Rsamtools_1.30.0           XVector_0.18.0            
[31] changepoint_2.2.2          BSgenome_1.46.0            rlang_0.2.0               
[34] GlobalOptions_0.0.12       RSQLite_2.0                shape_1.4.4               
[37] zoo_1.8-1                  mclust_5.4                 BiocParallel_1.12.0       
[40] gtools_3.5.0               VariantAnnotation_1.24.5   RCurl_1.95-4.10           
[43] magrittr_1.5               GenomeInfoDbData_1.0.0     wordcloud_2.5             
[46] Matrix_1.2-12              Rcpp_0.12.16               munsell_0.4.3             
[49] S4Vectors_0.16.0           viridis_0.5.0              stringi_1.1.7             
[52] yaml_2.1.18                SummarizedExperiment_1.8.1 zlibbioc_1.24.0           
[55] plyr_1.8.4                 FField_0.1.0               grid_3.4.3                
[58] blob_1.1.0                 ggrepel_0.7.0              lattice_0.20-35           
[61] Biostrings_2.46.0          cowplot_0.9.2              splines_3.4.3             
[64] GenomicFeatures_1.30.3     circlize_0.4.3             knitr_1.20                
[67] ComplexHeatmap_1.17.1      pillar_1.2.1               GenomicRanges_1.30.3      
[70] rjson_0.2.15               rngtools_1.2.4             reshape2_1.4.3            
[73] codetools_0.2-15           biomaRt_2.34.2             stats4_3.4.3              
[76] XML_3.98-1.10              foreach_1.4.4              gtable_0.2.0              
[79] assertthat_0.2.0           ggplot2_2.2.1              gridBase_0.4-7            
[82] xtable_1.8-2               viridisLite_0.3.0          survival_2.41-3           
[85] tibble_1.4.2               iterators_1.0.9            GenomicAlignments_1.14.1  
[88] AnnotationDbi_1.40.0       registry_0.5               memoise_1.1.0             
[91] IRanges_2.12.0             cluster_2.0.6             
```{r}

I was able to get the test code you sent working, I had to output the image to pdf file directly. 

```{r}
library(GenVisR)
tmp <- brcaMAF

tmp <- tmp[,c("Hugo_Symbol", "Variant_Classification", "Tumor_Sample_Barcode")]
colnames(tmp) <- c("gene", "variant_class", "sample")

pdf("tmp.pdf")
waterfall(tmp, fileType="Custom", variant_class_order=as.character(unique(tmp$variant_class)), mainXlabel=TRUE,rmvSilent=T)
dev.off()
```

**Comment by zlskidmore** [comment] 2018-03-15 18:52
Okay, that's odd, everything appears to be in order in what you sent. Can you try wrapping your input data in `na.omit()`.

```R
waterfall(na.omit(shortT001), fileType = "Custom", variant_class_order = as.character(unique(na.omit(shortT001$variant_class))), mainXlabel = TRUE, rmvSilent = T)
```
That's the only thing I can think of that might be causing an issue (though i'm not sure how yet). If the above works can you send me a few lines of your data frame that have been removed (i.e. had NA values).

If the above does not work would you be able to obfuscate your input data and send it to me, you could just rename the values in all the columns to protect your data (just need to make sure once you obfuscate the data that it still produces the error), it doesn't matter what they are, could be cities, etc., I would just need an example to debug from?

**Comment by kb472** [comment] 2018-03-15 19:52
I'm getting the same error when I try the command you sent me:
`waterfall(na.omit(shortT001), fileType = "Custom", variant_class_order = as.character(unique(na.omit(shortT001$variant_class))), mainXlabel = TRUE, rmvSilent = T)
Checking if input is properly formatted...
Detected "Custom" file_type flag, looking for correct column names...
Calculating frequency of mutations...
Removing silent mutations...
setting mutation hierarchy...
Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  : 
  factor level [2] is duplicated`

I am checking with my supervisor regarding the data share, so will get back to you on that.Thank you

**Comment by zlskidmore** [comment] 2018-03-15 20:06
Okay, I'm not sure what else to suggest without having something to reproduce the error so I can start debugging. Again, it doesn't have to be your exact data (**I would actually prefer it wasn't**) you can obscure it by changing gene/sample names/variant names etc. or rearranging and subsetting those values for those variables so they are biologically meaningless. The `waterfall()` function doesn't actually care what the names are.

If it is to much work to obfuscate the data and send a reproduceable example the only suggestion I can make is to update GenVisR to the devel version currently at 1.11.0. in this version there is a new Waterfall function with capital W `Waterfall()` that has been re-written from the ground up and is significantly different from the old version. It won't be released on bioconductor till May but I can provide instructions for installing the devel version and running the new function if you wish to ry this approach, just let me know.

**Comment by kb472** [comment] 2018-03-15 20:34
Thank you, Yes I understand I can replace the values, but I still have to get permission. I am in the process of getting permission from my supervisor. 
In the mean time, I would love to try out the new Waterfall() function. Would be great if you could give some examples and instructions. Thank you !

**Comment by zlskidmore** [comment] 2018-03-15 20:54
you can install the new GenVisR with the following code:

```R
library("devtools")
devtools::install_github("griffithlab/GenVisR")
```
Note that using this method requires you to install R package dependencies manually if they are not already installed, you can find a list of these in the description file here (anything in the imports field):
https://github.com/griffithlab/GenVisR/blob/master/DESCRIPTION

these can be installed with the typical `install.package()` command for cran packages and through bioconductor

if successful you should notice your GenVisR version at 1.11.0

from there you might find this vignette helpful though it's a work in progress:
https://bioconductor.org/packages/devel/bioc/vignettes/GenVisR/inst/doc/Visualizing_Small_Variants.html

but basically you need to load your data into R as a data.table instead of a data.frame, see the function `fread()` from the data.table package and supply that to `Waterfall()` note: it must have column names "sample", "gene", "mutation". Because this is custom data you also need to pass a data.table to the param `mutationHierarchy` with the column names "mutation", "color", this replaces the old `variant_class_order ` param

use ?Waterfall to see a full list of parameters for the new function, many should be familiar

**Comment by kb472** [comment] 2018-03-16 12:17
Please see attached the data frame in tab delimited format. I am able to reproduce the error even after changing some of the values with country/city names

```{r}
input1 = read.table(file = "20180316TestKB.txt", sep="\t", row.names = F, quote = F, header = T, stringsAsFactors = F) 

input2 = na.omit(input1)
 
waterfall(input2, fileType = "Custom", variant_class_order = as.character(unique(input2$variant_class)), mainXlabel = TRUE, rmvSilent = T)

[20180316TestKB.txt](https://github.com/griffithlab/GenVisR/files/1819118/20180316TestKB.txt)
Checking if input is properly formatted...
Detected "Custom" file_type flag, looking for correct column names...
Did not detect silent mutations in input, is this expected?Calculating frequency of mutations...
Removing silent mutations...
setting mutation hierarchy...
Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  : 
  factor level [2] is duplicated
```

**Comment by zlskidmore** [comment] 2018-03-16 19:41
thanks @kb472 !

After some trouble shooting I think the problem is that your input data contains only 1 sample. I never expected to encounter this with this type of plot however it is a bug. I've pushed a fix up to bioconductor it should be available sometime tomorrow. To verify that this was indeed the issue you encountered can you change one of the rows in your original input so two different samples are in the sample column?

**Comment by kb472** [comment] 2018-03-19 18:56
Thanks ! Yes, everything is working now. 

I do have another question - not sure if I should start a new thread or write it here:

I have VCF from my RNA-seq experiment.  I converted the VCF files to MAF files two ways: (a) with the vcf2maf tool and (b) with the annovarToMaf() function from maftools. Once I get a MAF file for each of my samples, I merge them all to create the "multi sample" MAF file. Then I read them into R and pull out the 3 columns of interest - sample id, variant class and gene symbol.
When I apply the waterfall plot to this dataframe to show the top 50 genes, I get a waterfall plot where each sample has a missense mutation (Attached). There is something wrong because there are too many mutations listed. No matter what method I use to convert VCF to MAF, I get the same image. 
Any idea why there are too many missense mutations ? 
Any idea what I am doing wrong here ? Any advise is helpful. Thank you !
<img width="705" alt="screen shot 2018-03-19 at 2 52 43 pm" src="https://user-images.githubusercontent.com/1800604/37616233-a4ef0472-2b85-11e8-907e-208c4334ced7.png">

**Comment by zlskidmore** [comment] 2018-03-19 19:31
I've not seen anything like this problem before. Is it possible that when you did the merge it duplicated mutations on a sample basis?

Maybe start by finding a case that you know should be without a mutation and check your original input data frame to make sure it's not there and also run waterfall with `out="data"` to see if it's in the final output from GenVisR.

**Closed** 2018-06-22 18:39 UTC
