### ISSUE TITLE
Error downloading and reading the library (No package called FField)

### ISSUE THREAD

**Issue by Sudheshna30** [griffithlab/GenVisR#387] opened 2022-07-14 03:54 UTC
Error: package or namespace load failed for ‘GenVisR’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘FField’

**Comment by blackbeerd** [comment] 2022-07-14 04:02
I was just searching for a solution for similar error and saw this posted. 
Trying to install genvisr on a linux cluster in a conda R=4.2 environment. "FFiled not available for this version of R"

But the Bioc page for this says to open R (4.2) and install GenVisR...? https://bioconductor.org/packages/release/bioc/html/GenVisR.html

Is this a version mistake?

**Comment by Sudheshna30** [comment] 2022-07-14 04:04
> I was just searching for a solution for similar error... Trying to install genvisr on a linux cluster in a conda R=4.2 environment. "FFiled not available for this version of R"
> 
> But the Bioc page for this says to open R (4.2) and install GenVisR...? https://bioconductor.org/packages/release/bioc/html/GenVisR.html
> 
> Is this a version mistake?

Im not sure. I'm on the same version of R and the same thing confused me as well

**Comment by blackbeerd** [comment] 2022-07-14 04:07
Thanks for the sanity check! Let me know if you find a solution (I will as well). I was thinking of trying to install with an earlier version of Bioc (and R), but I haven't checked how recent the FField package (which version of R, that is)...

**Comment by blackbeerd** [comment] 2022-07-14 04:35
> > I was just searching for a solution for similar error... Trying to install genvisr on a linux cluster in a conda R=4.2 environment. "FFiled not available for this version of R"
> > But the Bioc page for this says to open R (4.2) and install GenVisR...? https://bioconductor.org/packages/release/bioc/html/GenVisR.html
> > Is this a version mistake?
> 
> Im not sure. I'm on the same version of R and the same thing confused me as well

Thanks for the sanity check! Let me know if you find a solution (I will as well). I was thinking of trying to install with an earlier version of Bioc (and R), but I haven't checked how recent the FField package (which version of R, that is)...

**Comment by Sudheshna30** [comment] 2022-07-14 04:50
> > > I was just searching for a solution for similar error... Trying to install genvisr on a linux cluster in a conda R=4.2 environment. "FFiled not available for this version of R"
> > > But the Bioc page for this says to open R (4.2) and install GenVisR...? https://bioconductor.org/packages/release/bioc/html/GenVisR.html
> > > Is this a version mistake?
> > 
> > 
> > Im not sure. I'm on the same version of R and the same thing confused me as well
> 
> Thanks for the sanity check! Let me know if you find a solution (I will as well). I was thinking of trying to install with an earlier version of Bioc (and R), but I haven't checked how recent the FField package (which version of R, that is)...


I found this
https://cran.r-project.org/web/packages/FField/index.html

**Comment by blackbeerd** [comment] 2022-07-14 05:23
> > > > I was just searching for a solution for similar error... Trying to install genvisr on a linux cluster in a conda R=4.2 environment. "FFiled not available for this version of R"
> > > > But the Bioc page for this says to open R (4.2) and install GenVisR...? https://bioconductor.org/packages/release/bioc/html/GenVisR.html
> > > > Is this a version mistake?
> > > 
> > > 
> > > Im not sure. I'm on the same version of R and the same thing confused me as well
> > 
> > 
> > Thanks for the sanity check! Let me know if you find a solution (I will as well). I was thinking of trying to install with an earlier version of Bioc (and R), but I haven't checked how recent the FField package (which version of R, that is)...
> 
> I found this https://cran.r-project.org/web/packages/FField/index.html

So I got mine working.

Here's what I did, not sure it's applicable to your situation?\
1) in R (version 4.2) I installed the devel version of Bioc (https://contributions.bioconductor.org/use-devel.html) 
\\\if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "devel")\\\

I reran GenVisR install in R 
\\\BiocManager::install("GenVisR")\\\

and saw that stringi was not installing, so I quit R and installed via conda in bash. This thread was useful: https://github.com/gagolews/stringi/issues/302

2) conda install -c conda-forge r-stringi
3) Started R
4) Ran GenVisR install again (BiocManager::install("GenVisR")), but enter "n" when it asked if I wanted to update stringi.
5) Loaded GenVisR library (library(GenVisR))
6) Tried the sample data follow waterfall plot tutorial here: https://genviz.org/module-03-genvisr/0003/02/01/waterfall_GenVisR/

Good luck!
 
2)

**Comment by Sudheshna30** [comment] 2022-07-14 06:45
@blackbeerd downloading devel and running GenVis worked for me! Thanks to you!

**Comment by Sudheshna30** [comment] 2022-07-14 14:00
> re-opening this, the FField package is now deprecated, it's only used in the lolliplot() function, and i have a working replacement I just need to strip out the dependency and the old lolliplot function

@zlskidmore  May I know how to do that?

**Comment by zlskidmore** [comment] 2022-07-14 15:50
if you clone the repo, you'll find FField calls in the DESCRIPTION and NAMESPACE files, they need to be removed, along with the entire lolliplot() function which is located in R/deprecated.R

**Comment by bounlu** [comment] 2022-08-01 03:09
Will you push the fixed version soon?

**Comment by zlskidmore** [comment] 2022-08-01 16:21
Currently at a conference, it should be pushed by end of the week

**Comment by Hejhacz** [comment] 2022-08-21 19:58
Hello! 

@zlskidmore Could I know when the fixed version will be available to install? 

I'm a newbie and really would like to use GenVisR but I do not know how to deal with this FField error :(

**Comment by csmatyi** [comment] 2022-08-26 17:13
> BiocManager::install("GenVisR")

I tried doing what you said but no luck, FField still keeps coming up:
My error:

----

 library("GenVisR")
Error: package or namespace load failed for ‘GenVisR’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘FField’

**Comment by mheskett** [comment] 2022-09-02 18:11
> > > > > I was just searching for a solution for similar error... Trying to install genvisr on a linux cluster in a conda R=4.2 environment. "FFiled not available for this version of R"
> > > > > But the Bioc page for this says to open R (4.2) and install GenVisR...? https://bioconductor.org/packages/release/bioc/html/GenVisR.html
> > > > > Is this a version mistake?
> > > > 
> > > > 
> > > > Im not sure. I'm on the same version of R and the same thing confused me as well
> > > 
> > > 
> > > Thanks for the sanity check! Let me know if you find a solution (I will as well). I was thinking of trying to install with an earlier version of Bioc (and R), but I haven't checked how recent the FField package (which version of R, that is)...
> > 
> > 
> > I found this https://cran.r-project.org/web/packages/FField/index.html
> 
> So I got mine working.
> 
> Here's what I did, not sure it's applicable to your situation?\
> 
> 1. in R (version 4.2) I installed the devel version of Bioc (https://contributions.bioconductor.org/use-devel.html)
>    if (!requireNamespace("BiocManager", quietly=TRUE))
>    install.packages("BiocManager")
>    BiocManager::install(version = "devel")
> 
> 1a) I reran GenVisR install in R BiocManager::install("GenVisR")
> 
> and saw that stringi was not installing, so I quit R and installed via conda in bash. This thread was useful: [gagolews/stringi#302](https://github.com/gagolews/stringi/issues/302) - suggests apt install instead of conda if you're not using conda
> 
> 2. conda install -c conda-forge r-stringi
> 3. Started R
> 4. Ran GenVisR install again (BiocManager::install("GenVisR")), but enter "n" when it asked if I wanted to update stringi.
> 5. Loaded GenVisR library (library(GenVisR))
> 6. Tried the sample data following commands in waterfall plot tutorial here: https://genviz.org/module-03-genvisr/0003/02/01/waterfall_GenVisR/
> 
> Good luck!

thanks for this. at that point using the package is not worth it because i could spend days trying to reproduce this. hopefully the developers are willing to help out!

**Comment by zlskidmore** [comment] 2022-09-04 21:59
I appreciate everyone's patience a fix has been pushed up, you should be able to install from github now, or from the bioc-devel branch once the nightly builds complete. Please re-open if there are still issues after 24 hours.

**Closed by zlskidmore** 2022-09-04 21:59 UTC

**Comment by jon4thin** [comment] 2023-11-08 19:51
I am unable to get Lolliplot() to work and I am not sure if this is expected or not:
https://github.com/griffithlab/GenVisR/issues/394
